import { createClient } from '@supabase/supabase-js';
import { ethers } from 'ethers';
import dotenv from 'dotenv';

// Load env
dotenv.config({ path: '.env.local' });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

console.log('--- Full Stack Verification Script ---');
console.log(`Supabase URL: ${supabaseUrl}`);
console.log(`Supabase Key Length: ${supabaseKey?.length}`);

async function main() {
    if (!supabaseUrl || !supabaseKey) {
        console.error('❌ Missing Env Vars');
        process.exit(1);
    }

    // 1. Verify Supabase Connection & Auth
    console.log('\n[1] Verifying Supabase Auth & DB...');
    const supabase = createClient(supabaseUrl, supabaseKey);
    const testEmail = `verifier_${Date.now()}@ai-university.edu`;
    const testPass = 'password123';

    try {
        console.log(`    Attempting Signup: ${testEmail}`);
        const { data: authData, error: authError } = await supabase.auth.signUp({
            email: testEmail,
            password: testPass
        });

        if (authError) throw authError;

        const user = authData.user;
        if (!user) throw new Error('User creation failed (no user object)');
        console.log(`    ✅ User Created: ${user.id}`);

        // 2. Verify Profile Creation
        // Wait a moment for triggers
        await new Promise(r => setTimeout(r, 2000));

        console.log('    Checking Profile...');
        const { data: profile, error: profileError } = await supabase
            .from('profiles')
            .select('*')
            .eq('user_id', user.id)
            .single();

        if (profileError) {
            console.warn(`    ⚠️ Profile fetch failed: ${profileError.message} (Is the trigger set up?)`);
        } else {
            console.log(`    ✅ Profile Found: XP=${profile.xp}`);
        }

        // 3. Mimic Course Generation
        console.log('\n[2] Verifying Course Creation...');
        const courseData = {
            user_id: user.id,
            title: 'Web3 Verification Course',
            description: 'Generated by verification script',
            skill_level: 'Beginner',
            jsonb_content: { modules: [{ title: 'Module 1', content: 'Content' }] }
        };

        const { data: course, error: courseError } = await supabase
            .from('courses')
            .insert(courseData)
            .select()
            .single();

        // Note: checking error but continuing if table RLS prevents insert (though anon should be able to if authenticated)
        if (courseError) {
            console.error(`    ❌ Course Creation Failed: ${courseError.message}`);
        } else {
            console.log(`    ✅ Course Created: ${course.id}`);
        }

        // 4. Mimic Quiz Completion (Update XP)
        console.log('\n[3] Verifying XP Update...');
        const { error: xpError } = await supabase
            .from('profiles')
            .update({ xp: 500 })
            .eq('user_id', user.id);

        if (xpError) {
            console.error(`    ❌ XP Update Failed: ${xpError.message}`);
        } else {
            console.log('    ✅ XP Updated to 500');
        }

        // 5. Leaderboard Check
        console.log('    Checking Leaderboard...');
        const { data: lb } = await supabase.from('leaderboard').select('*').limit(5);
        if (lb) {
            const myEntry = lb.find(e => e.email === testEmail);
            if (myEntry) {
                console.log(`    ✅ Found user in Leaderboard at Rank ${lb.indexOf(myEntry) + 1}`);
            } else {
                console.warn('    ⚠️ User not in Top 5 (Might need more XP or leaderboard view refresh)');
                console.log('    Current Top:', lb.map(u => `${u.email}: ${u.xp}XP`));
            }
        }

    } catch (e) {
        console.error(`    ❌ Backend Verification Failed: ${e.message}`);
        // process.exit(1); // Continue to contract check
    }

    // 6. Smart Contract Logic Check
    console.log('\n[4] Verifying Smart Contract Logic...');
    const rpc = process.env.SEPOLIA_RPC_URL;
    const key = process.env.DEPLOYER_PRIVATE_KEY;

    if (!rpc || !key) {
        console.warn('    ⚠️ Missing RPC/Key for contract check.');
    } else {
        try {
            const provider = new ethers.JsonRpcProvider(rpc);
            const network = await provider.getNetwork();
            console.log(`    ✅ Connected to Network: ${network.name} (Chain ID: ${network.chainId})`);

            const wallet = new ethers.Wallet(key, provider);
            console.log(`    ✅ Deployer Wallet: ${wallet.address}`);

            const balance = await provider.getBalance(wallet.address);
            console.log(`    ✅ Balance: ${ethers.formatEther(balance)} ETH`);
        } catch (e) {
            console.error(`    ❌ Contract Connection Failed: ${e.message}`);
        }
    }

    console.log('\n--- Verification Complete ---');
}

main();
